version: "3"

services:
  web:
    container_name: proyecto_node
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo

  mongo:
    container_name: mongo_database
    image: mongo
    ports:
      - "27018:27017"